### ISSUE TITLE
Buggy Alumni Association Looking for Access

### ISSUE THREAD

**Issue by ahundt** [CMUBuggy/Guidebook#1]
Hey, @sweepstakes or other people involved with this repo, this is Andrew Hundt and I was the 2009 Sweepstakes Chairman. @krishantaylor is hoping to get BAA access to the CMUBuggy organization to create repos for the BAA website, could whomever controls this add him to the org with full permissions?

Hopefully somebody will see this :-)

**Comment by sweepstakes** [comment]
Ben Matzke is the man you want to look for.
Ben.Matzke@cmubuggy.org

**Comment by krishantaylor** [comment]
So it's not Ben or Sam. @bjcohen, is it you?

**Comment by bjcohen** [comment]
@krishantaylor Done. Apparently it is me. Actually not sure how I ended up being an owner of this org /shrug.
